import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import { v4 as uuidv4 } from "uuid";
import { OrderTable, OrderStatus } from "src/payment/entities/order.entity";

@Injectable()
export class OrderSeedService {
  constructor(
    @InjectRepository(OrderTable)
    private readonly orderRepository: Repository<OrderTable>
  ) {}

  async run() {
    await this.seedOrders();
  }

  private async seedOrders() {
    const orders = [
      {
        id: uuidv4(),
        userId: null,
        productId: null,
        serviceId: null,
        subProduct: null,
        subService: null,
        ownedDigifranchise: null,
        orderAdditionalInfo: [],
        quantity: 1,
        orderNumber: 1001,
        orderCode: "ORD001",
        unitPrice: "10.00",
        totalAmount: 10.0,
        status: OrderStatus.PENDING,
        vatAmount: null,
        deleteAt: null,
      },
      {
        id: uuidv4(),
        userId: null,
        productId: null,
        serviceId: null,
        subProduct: null,
        subService: null,
        ownedDigifranchise: null,
        orderAdditionalInfo: [],
        quantity: 2,
        orderNumber: 1002,
        orderCode: "ORD002",
        unitPrice: "20.00",
        totalAmount: 40.0,
        status: OrderStatus.PENDING,
        vatAmount: null,
        deleteAt: null,
      },
      {
        id: uuidv4(),
        userId: null,
        productId: null,
        serviceId: null,
        subProduct: null,
        subService: null,
        ownedDigifranchise: null,
        orderAdditionalInfo: [],
        quantity: 1,
        orderNumber: 1003,
        orderCode: "ORD003",
        unitPrice: "30.00",
        totalAmount: 30.0,
        status: OrderStatus.PROCESSING,
        vatAmount: null,
        deleteAt: null,
      },
      {
        id: uuidv4(),
        userId: null,
        productId: null,
        serviceId: null,
        subProduct: null,
        subService: null,
        ownedDigifranchise: null,
        orderAdditionalInfo: [],
        quantity: 2,
        orderNumber: 1004,
        orderCode: "ORD004",
        unitPrice: "40.00",
        totalAmount: 80.0,
        status: OrderStatus.PROCESSING,
        vatAmount: null,
        deleteAt: null,
      },
      {
        id: uuidv4(),
        userId: null,
        productId: null,
        serviceId: null,
        subProduct: null,
        subService: null,
        ownedDigifranchise: null,
        orderAdditionalInfo: [],
        quantity: 1,
        orderNumber: 1005,
        orderCode: "ORD005",
        unitPrice: "50.00",
        totalAmount: 50.0,
        status: OrderStatus.SHIPPED,
        vatAmount: null,
        deleteAt: null,
      },
      {
        id: uuidv4(),
        userId: null,
        productId: null,
        serviceId: null,
        subProduct: null,
        subService: null,
        ownedDigifranchise: null,
        orderAdditionalInfo: [],
        quantity: 2,
        orderNumber: 1006,
        orderCode: "ORD006",
        unitPrice: "60.00",
        totalAmount: 120.0,
        status: OrderStatus.SHIPPED,
        vatAmount: null,
        deleteAt: null,
      },
      {
        id: uuidv4(),
        userId: null,
        productId: null,
        serviceId: null,
        subProduct: null,
        subService: null,
        ownedDigifranchise: null,
        orderAdditionalInfo: [],
        quantity: 1,
        orderNumber: 1007,
        orderCode: "ORD007",
        unitPrice: "70.00",
        totalAmount: 70.0,
        status: OrderStatus.DELIVERED,
        vatAmount: null,
        deleteAt: null,
      },
      {
        id: uuidv4(),
        userId: null,
        productId: null,
        serviceId: null,
        subProduct: null,
        subService: null,
        ownedDigifranchise: null,
        orderAdditionalInfo: [],
        quantity: 2,
        orderNumber: 1008,
        orderCode: "ORD008",
        unitPrice: "80.00",
        totalAmount: 160.0,
        status: OrderStatus.DELIVERED,
        vatAmount: null,
        deleteAt: null,
      },
      {
        id: uuidv4(),
        userId: null,
        productId: null,
        serviceId: null,
        subProduct: null,
        subService: null,
        ownedDigifranchise: null,
        orderAdditionalInfo: [],
        quantity: 1,
        orderNumber: 1009,
        orderCode: "ORD009",
        unitPrice: "90.00",
        totalAmount: 90.0,
        status: OrderStatus.CANCELLED,
        vatAmount: null,
        deleteAt: null,
      },
      {
        id: uuidv4(),
        userId: null,
        productId: null,
        serviceId: null,
        subProduct: null,
        subService: null,
        ownedDigifranchise: null,
        orderAdditionalInfo: [],
        quantity: 2,
        orderNumber: 1010,
        orderCode: "ORD010",
        unitPrice: "100.00",
        totalAmount: 200.0,
        status: OrderStatus.CANCELLED,
        vatAmount: null,
        deleteAt: null,
      },
      {
        id: uuidv4(),
        userId: null,
        productId: null,
        serviceId: null,
        subProduct: null,
        subService: null,
        ownedDigifranchise: null,
        orderAdditionalInfo: [],
        quantity: 1,
        orderNumber: 1011,
        orderCode: "ORD011",
        unitPrice: "110.00",
        totalAmount: 110.0,
        status: OrderStatus.RETURNED,
        vatAmount: null,
        deleteAt: null,
      },
      {
        id: uuidv4(),
        userId: null,
        productId: null,
        serviceId: null,
        subProduct: null,
        subService: null,
        ownedDigifranchise: null,
        orderAdditionalInfo: [],
        quantity: 2,
        orderNumber: 1012,
        orderCode: "ORD012",
        unitPrice: "120.00",
        totalAmount: 240.0,
        status: OrderStatus.RETURNED,
        vatAmount: null,
        deleteAt: null,
      },
      {
        id: uuidv4(),
        userId: null,
        productId: null,
        serviceId: null,
        subProduct: null,
        subService: null,
        ownedDigifranchise: null,
        orderAdditionalInfo: [],
        quantity: 1,
        orderNumber: 1013,
        orderCode: "ORD013",
        unitPrice: "130.00",
        totalAmount: 130.0,
        status: OrderStatus.DECLINED,
        vatAmount: null,
        deleteAt: null,
      },
      {
        id: uuidv4(),
        userId: null,
        productId: null,
        serviceId: null,
        subProduct: null,
        subService: null,
        ownedDigifranchise: null,
        orderAdditionalInfo: [],
        quantity: 2,
        orderNumber: 1014,
        orderCode: "ORD014",
        unitPrice: "140.00",
        totalAmount: 280.0,
        status: OrderStatus.DECLINED,
        vatAmount: null,
        deleteAt: null,
      },
      {
        id: uuidv4(),
        userId: null,
        productId: null,
        serviceId: null,
        subProduct: null,
        subService: null,
        ownedDigifranchise: null,
        orderAdditionalInfo: [],
        quantity: 1,
        orderNumber: 1015,
        orderCode: "ORD015",
        unitPrice: "150.00",
        totalAmount: 150.0,
        status: OrderStatus.COMPLETE,
        vatAmount: null,
        deleteAt: null,
      },
      {
        id: uuidv4(),
        userId: null,
        productId: null,
        serviceId: null,
        subProduct: null,
        subService: null,
        ownedDigifranchise: null,
        orderAdditionalInfo: [],
        quantity: 2,
        orderNumber: 1016,
        orderCode: "ORD016",
        unitPrice: "160.00",
        totalAmount: 320.0,
        status: OrderStatus.COMPLETE,
        vatAmount: null,
        deleteAt: null,
      },
    ];

    for (const orderData of orders) {
      const existingOrder = await this.orderRepository.findOne({
        where: { orderCode: orderData.orderCode },
      });

      if (!existingOrder) {
        const order = this.orderRepository.create(orderData);
        await this.orderRepository.save(order);
      } else {
        console.log(
          `Order with code ${orderData.orderCode} already exists. Skipping.`
        );
      }
    }
  }
}
