import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateQuotationsTable1723130229522 implements MigrationInterface {
    name = 'CreateQuotationsTable1723130229522'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "role" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "status" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_e12743a7086ec826733f54e1d95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "session" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid, CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d2f174ef04fb312fdebd0ddc5" ON "session" ("userId") `);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying, "phoneNumber" character varying, "password" character varying, "provider" character varying NOT NULL DEFAULT 'email', "socialId" character varying, "firstName" character varying, "lastName" character varying, "dateOfBirth" date, "image" character varying, "idImage" character varying, "gender" character varying, "race" character varying, "homeAddress" character varying, "educationLevel" character varying, "currentActivity" character varying, "fieldOfStudy" character varying, "qualifications" json, "professionalBody" json, "southAfricanCitizen" character varying, "documentId" character varying, "countryOfOrigin" character varying, "criminalRecord" character varying, "policeClearenceCertificate" character varying, "crimes" json, "isProfileComplete" boolean DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "deleteAt" TIMESTAMP, "roleId" integer, "statusId" integer, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "UQ_f2578043e491921209f5dadd080" UNIQUE ("phoneNumber"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9bd2fe7a8e694dedc4ec2f666f" ON "user" ("socialId") `);
        await queryRunner.query(`CREATE INDEX "IDX_58e4dbff0e1a32a9bdc861bb29" ON "user" ("firstName") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0e1b4ecdca13b177e2e3a0613" ON "user" ("lastName") `);
        await queryRunner.query(`CREATE INDEX "IDX_3bd3f2e16165d1dac3e8e13286" ON "user" ("image") `);
        await queryRunner.query(`CREATE INDEX "IDX_d03cc9951fbb73d092fa53127e" ON "user" ("idImage") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0f3f1de3c7590ddf4299b6596" ON "user" ("gender") `);
        await queryRunner.query(`CREATE INDEX "IDX_91c1ef85a7e6c89eaeec99bfd6" ON "user" ("race") `);
        await queryRunner.query(`CREATE INDEX "IDX_9086fd0adfc3fdd84a443dd1b1" ON "user" ("homeAddress") `);
        await queryRunner.query(`CREATE INDEX "IDX_083056026899d829066008244b" ON "user" ("educationLevel") `);
        await queryRunner.query(`CREATE INDEX "IDX_772c766ebfc783bb03fa5e3404" ON "user" ("currentActivity") `);
        await queryRunner.query(`CREATE INDEX "IDX_a5e03f420f37f1f2270ec3f7a9" ON "user" ("fieldOfStudy") `);
        await queryRunner.query(`CREATE TABLE "supplier_management" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fullNames" text NOT NULL, "email" character varying NOT NULL, "mobile_number" character varying NOT NULL, "supplier_type" character varying NOT NULL, "company_registration_number" character varying, "vat_number" character varying, "address" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "userId" uuid, "ownedDigifranchise" uuid, CONSTRAINT "PK_10f8e6846ede50b63f2fb758d22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customer_management" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fullNames" text NOT NULL, "email" character varying NOT NULL, "mobile_number" character varying NOT NULL, "customer_type" character varying NOT NULL, "company_registration_number" character varying, "vat_number" character varying, "address" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "userId" uuid, "ownedDigifranchise" uuid, CONSTRAINT "PK_a3cc08741e7a6b80e5a7305083a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "digifranchise" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "digifranchiseName" character varying(255), "digifranchiseImg" character varying, "description" text, "status" character varying(255) NOT NULL DEFAULT '2', "digifranchiseFee" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, CONSTRAINT "PK_b4e302f70d8b71fff39535ce172" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "digifranchise_general_info" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ownedDigifranchiseId" uuid, "digifranchiseName" character varying NOT NULL, "facebookHandle" character varying NOT NULL, "tiktokHandle" character varying NOT NULL, "instagramHandle" character varying NOT NULL, "xHandle" character varying NOT NULL, "address" character varying NOT NULL, "connectNumberWithOutCountryCode" character varying NOT NULL, "connectNumber" character varying NOT NULL, "otherMobileNumberWithOutCountryCode" character varying NOT NULL, "otherMobileNumber" character varying NOT NULL, "useOtherMobileNumberForWebsite" boolean NOT NULL DEFAULT false, "aboutCompany" character varying NOT NULL, "location" character varying NOT NULL, "digifranchisePublished" boolean NOT NULL DEFAULT false, "digifranchisePublishedWithCC" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, CONSTRAINT "REL_628ee3d8e80b874079732697d6" UNIQUE ("ownedDigifranchiseId"), CONSTRAINT "PK_3e04643b9802b6e9df3c9940334" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "digifranchise_compliance_info" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ownedDigifranchiseId" uuid, "companyRegisterationNumber" character varying, "taxNumber" character varying, "taxClearencePin" character varying, "taxClearenceExpiration" character varying, "coidaRegisteration" character varying, "vatNumber" character varying, "uifRegistration" character varying, "workMansCompensation" character varying, "sdlNumber" character varying, "otherComplianceDocs" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, CONSTRAINT "REL_aaf18ed9b15cc56f76043dc0d5" UNIQUE ("ownedDigifranchiseId"), CONSTRAINT "PK_a1fa2dda83341520b251af11b4e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "digifranchise_service_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "serviceCategoryName" character varying(255) NOT NULL, "unitPrice" character varying(255) NOT NULL, "description" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "serviceId" uuid, CONSTRAINT "PK_63547c1f159022c8b1caf7fb634" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quotations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "digifranchiseUrl" character varying(255) NOT NULL, "isOrdered" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "ownedDigifranchiseId" uuid, CONSTRAINT "PK_6c00eb8ba181f28c21ffba7ecb1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quotationItems" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" integer NOT NULL, "price" numeric NOT NULL, "expiryDate" TIMESTAMP, "provisionHours" TIMESTAMP, "quotation" uuid, "product" uuid, "service" uuid, CONSTRAINT "PK_1a09ce43bf32ebe029cf45a5760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "digifranchise_product" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productName" text NOT NULL, "description" text NOT NULL, "unitPrice" character varying(255) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "digifranchiseId" uuid, "userId" uuid, "digifranchiseOwnedId" uuid, CONSTRAINT "PK_d0a78c3c6099881ff03408a6466" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "digifranchise_select_product_or_service_table" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isSelected" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "ownerDigifranchise" uuid, "digifranchiseService" uuid, "franchiseProduct" uuid, "userId" uuid, CONSTRAINT "PK_b6c83ba81cb8647be16b2ccacfd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "digifranchise_service_offered" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "serviceName" text NOT NULL, "description" text NOT NULL, "unitPrice" character varying(255) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "digifranchiseId" uuid, "userId" uuid, "digifranchiseOwnedId" uuid, CONSTRAINT "PK_afa74ced0cfc1ef27e818336d08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "digifranchise_sub_product" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productName" text NOT NULL, "description" text NOT NULL, "unitPrice" character varying(255) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "digifranchiseProductId" uuid, "userId" uuid, "digifranchiseOwnedId" uuid, CONSTRAINT "PK_800edce848e1bcb7658f502ade4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "digifranchise_sub_service_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "serviceCategoryName" character varying(255) NOT NULL, "unitPrice" character varying(255) NOT NULL, "description" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "subServiceId" uuid, CONSTRAINT "PK_452b4401dc0cbc16524e5c1db24" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "digifranchise_sub_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "serviceName" text NOT NULL, "description" text NOT NULL, "unitPrice" character varying(255) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "digifranchiseServiceId" uuid, "digifranchiseOwnedId" uuid, "userId" uuid, CONSTRAINT "PK_c54cc8929973fcde392c5c9825d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "digifranchise_gallery_image" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "imageUrl" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "digifranchiseServiceId" uuid, "digifranchiseProductId" uuid, "subServiceId" uuid, "subProductId" uuid, "digifranchiseOwnedId" uuid, CONSTRAINT "PK_2fba0ba82713da62f7f416d6232" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fixed_expense_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fixedExpense" character varying(255) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "userId" uuid, CONSTRAINT "UQ_0c2eda1361b7154b738c26b5471" UNIQUE ("fixedExpense"), CONSTRAINT "PK_7854a2cc680e3044f754d290afc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "digifranchise_expense" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" integer NOT NULL, "unityCost" numeric(10,2) NOT NULL, "purchaseDone" boolean NOT NULL DEFAULT false, "puchaseDate" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "ownedDigifranchise" uuid, "fixedExpense" uuid, CONSTRAINT "PK_c08febf813d9fe86fa62a407f50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."available_management_allowedtimeslotunits_enum" AS ENUM('15', '30', '60', '90')`);
        await queryRunner.query(`CREATE TYPE "public"."available_management_mintimebetweenbookedslots_enum" AS ENUM('15', '30', '60')`);
        await queryRunner.query(`CREATE TABLE "available_management" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "weekDaysAndTimes" json NOT NULL, "allowedTimeSlotUnits" "public"."available_management_allowedtimeslotunits_enum" NOT NULL DEFAULT '30', "minTimeBetweenBookedSlots" "public"."available_management_mintimebetweenbookedslots_enum" NOT NULL DEFAULT '15', "allowBookingOnPublicHolidays" boolean NOT NULL DEFAULT false, "unavailableTime" json NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "userId" uuid, "ownedDigifranchise" uuid, CONSTRAINT "PK_6076db187aa80e2f90c870ea536" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unavailable_management" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "unavailableTime" json NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "userId" uuid, "ownedDigifranchise" uuid, "AvailableManagementId" uuid, CONSTRAINT "PK_00cc3c7d613160a9487b89170ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_management" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" text NOT NULL, "quantity" numeric(10,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "userId" uuid, "ownedDigifranchise" uuid, CONSTRAINT "PK_21865e7b0de8e2bd9f26f24539e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staff_management" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "image" text NOT NULL, "fullNames" text NOT NULL, "email" text NOT NULL, "mobile_number" text NOT NULL, "id_or_passport_number" text NOT NULL, "date_of_birth" TIMESTAMP NOT NULL DEFAULT now(), "role_description" text NOT NULL, "address" text NOT NULL, "date_started" TIMESTAMP NOT NULL DEFAULT now(), "app_access" boolean NOT NULL, "registration_method" text NOT NULL, "tax_number" text NOT NULL, "uif_number" text NOT NULL, "gross_monthly_salary" numeric(10,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "userId" uuid, "ownedDigifranchise" uuid, CONSTRAINT "PK_929d7f1350ca2762a37653495b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "calender_venue" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255), "location" text NOT NULL, "capacity" integer, "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "ownedFranchiseId" uuid, CONSTRAINT "PK_bf6e344b68f535c9a814a78b4a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."availability_allowedtimeslotunits_enum" AS ENUM('15', '30', '60', '90')`);
        await queryRunner.query(`CREATE TYPE "public"."availability_breaktimebetweenbookedslots_enum" AS ENUM('15', '30', '60')`);
        await queryRunner.query(`CREATE TABLE "availability" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "allowedTimeSlotUnits" "public"."availability_allowedtimeslotunits_enum" NOT NULL DEFAULT '30', "breakTimeBetweenBookedSlots" "public"."availability_breaktimebetweenbookedslots_enum" NOT NULL DEFAULT '15', "allowBookingOnPublicHolidays" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "userId" uuid, "ownedDigifranchise" uuid, CONSTRAINT "PK_05a8158cf1112294b1c86e7f1d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "availability_week_days" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "day" character varying(255) NOT NULL, "workingDate" TIMESTAMP, "isDayFullBooked" boolean NOT NULL DEFAULT false, "availabilityCounts" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "availabilityId" uuid, "ownedDigifranchise" uuid, "unavailabilityId" uuid, "availabilitySlotsDetailsId" uuid, CONSTRAINT "PK_598829a14e3e7bde460195fb0a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "availability_day_time" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "isBooked" boolean NOT NULL DEFAULT false, "availableTimeSlots" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "weekDay" uuid, "availabilityId" uuid, "ownedDigifranchise" uuid, "availabilitySlotsDetailsId" uuid, CONSTRAINT "PK_2425a3a697cb9750d6d520e59d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unavailability" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "workingDate" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "userId" uuid, "ownedDigifranchise" uuid, "availabilityWeekDaysId" uuid, "availabilityId" uuid, CONSTRAINT "PK_176e6b52ee1b44acea3b66e8aac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "availability_slots_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isSlotBooked" boolean NOT NULL DEFAULT false, "availabilityTimeSlotsDetails" json, "workingDate" TIMESTAMP, "day" character varying(255) NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "availabilityDayTime" uuid, "availabilityWeekDays" uuid, "ownedDigifranchise" uuid, "availabilityId" uuid, CONSTRAINT "PK_76739667fc3e9b922c625c41ae9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "availability_slots_time_one_one" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isSlotBooked" boolean NOT NULL DEFAULT false, "singleAvailabilityTimeSlots" json, "workingDate" TIMESTAMP, "day" character varying(255) NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "availabilityDayTime" uuid, "availabilityWeekDays" uuid, "ownedDigifranchise" uuid, "availabilityId" uuid, CONSTRAINT "PK_d1882549935795f21647282b601" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "availability_booked_slots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "userId" uuid, "slotId" uuid, CONSTRAINT "PK_258a7f6173962f2ceb02c31d363" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."digifranchise_working_hours_allowedtimeslotunits_enum" AS ENUM('15', '30', '60', '90')`);
        await queryRunner.query(`CREATE TYPE "public"."digifranchise_working_hours_breaktimebetweenbookedslots_enum" AS ENUM('15', '30', '60')`);
        await queryRunner.query(`CREATE TABLE "digifranchise_working_hours" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "allowedTimeSlotUnits" "public"."digifranchise_working_hours_allowedtimeslotunits_enum" NOT NULL DEFAULT '30', "breakTimeBetweenBookedSlots" "public"."digifranchise_working_hours_breaktimebetweenbookedslots_enum" NOT NULL DEFAULT '15', "allowBookingOnPublicHolidays" boolean NOT NULL DEFAULT false, "availabilityWeekDays" json, "unavailability" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "ownedDigifranchise" uuid, CONSTRAINT "PK_f9584ef98adc86fa7e32fbf6af7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "digifranchise_owner" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userEmail" character varying(255) NOT NULL, "digifranchiseId" character varying(255) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "userId" uuid, "digifranchise" uuid, CONSTRAINT "PK_c2e97b38553384a30b7eaa2119d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_issue_table" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "issue_description" text NOT NULL, "isSelected" boolean NOT NULL DEFAULT false, "orderAdditionalInfo" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "orderId" uuid, CONSTRAINT "PK_5217487197177105c8fcf28caaa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_complaints_table" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "issues" json, "additional_information" text NOT NULL, "refund_requested" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "orderId" uuid, "orderIssueId" uuid, CONSTRAINT "PK_54f300ba262fc3d8ae7fbd91098" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_table_status_enum" AS ENUM('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', 'DECLINED', 'COMPLETE')`);
        await queryRunner.query(`CREATE TABLE "order_table" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderAdditionalInfo" json, "quantity" integer NOT NULL, "orderNumber" integer NOT NULL, "orderCode" character varying NOT NULL, "unitPrice" character varying(255) NOT NULL, "totalAmount" numeric(10,2) NOT NULL, "status" "public"."order_table_status_enum" NOT NULL DEFAULT 'PENDING', "OrderDate" TIMESTAMP NOT NULL DEFAULT now(), "vatAmount" numeric(10,2), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "userId" uuid, "productId" uuid, "serviceId" uuid, "subProduct" uuid, "subService" uuid, "ownedDigifranchise" uuid, CONSTRAINT "PK_2e52c3d2ee23b941afed22f6a38" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_basic_info" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fullNames" text NOT NULL, "contactDetails" text NOT NULL, "address" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "order" uuid, CONSTRAINT "PK_d7750262a8c5631f16cefe50401" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rating_order_table" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rating" integer NOT NULL, "review" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "userId" uuid, "orderId" uuid, CONSTRAINT "PK_65a008f02114793284e2184790a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "accreditation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "accreditationName" character varying NOT NULL, "professionalBodyId" uuid NOT NULL, CONSTRAINT "PK_1aa1d5e25cfdf9c0f99a74c9157" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "professional_body_entity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "professionalBodyName" character varying NOT NULL, CONSTRAINT "PK_f7ebcc316bdf5260b21ada5e54a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rate_table" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rateName" character varying(255) NOT NULL, "rateNumber" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, CONSTRAINT "PK_8cb5ecb6da6da404b2cbfae4c30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" integer NOT NULL, "costPerItem" integer NOT NULL, "totalValue" integer NOT NULL, "dateReceived" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "inventoryId" uuid NOT NULL, CONSTRAINT "PK_1528e3203da22723e29566514f1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "franchiseId" character varying NOT NULL, "itemName" character varying(255) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, CONSTRAINT "PK_82aa5da437c5bbfb80703b08309" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "file" ("id" SERIAL NOT NULL, "filename" character varying NOT NULL, "filePath" character varying NOT NULL, "url" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, CONSTRAINT "PK_36b46d232307066b3a2c9ea3a1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "enquiries_table" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "names" text NOT NULL, "phone_number" integer NOT NULL, "email" text NOT NULL, "description" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "digifranchiseOwnerId" uuid, CONSTRAINT "PK_acc6907713479996e83966f5f83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customer_subscription" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "userId" uuid, "digifranchiseOwnerId" uuid, CONSTRAINT "PK_1a570a0f1783fbcf6123f18751f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "digifranchise_professional_body_membership" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ownedDigifranchiseId" character varying NOT NULL, "professionalOrganizationId" character varying NOT NULL, "accreditationId" character varying NOT NULL, "renewalDate" character varying NOT NULL, "documents" json NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, CONSTRAINT "PK_dc8fefde0a7baa2b9d683b97be0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "consultation_table" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "additionalInfo" character varying, "bookedTimeSlots" json, "contactInfo" json NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "ownedDigifranchise" uuid, CONSTRAINT "PK_969dedbf7e73dfb50ec233f0760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "calender_event_guest" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "customerId" uuid, "eventId" uuid, CONSTRAINT "PK_4db8f464545f64578e87f22e18c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "calender_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "description" text, "startTime" TIMESTAMP NOT NULL, "endTime" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "userId" uuid, "venueId" uuid, CONSTRAINT "PK_1f6cd347cfa262cd2593bf004a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "calender_event_owner" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "eventId" uuid, "userId" uuid, CONSTRAINT "PK_dd664736ef1e94ecb58038f6b38" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."calender_booking_status_enum" AS ENUM('confirmed', 'pending', 'cancelled', 'rescheduled', 'no_show', 'completed', 'in_progress')`);
        await queryRunner.query(`CREATE TABLE "calender_booking" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."calender_booking_status_enum" NOT NULL DEFAULT 'pending', "attendees" integer, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "eventId" uuid, "userId" uuid, CONSTRAINT "PK_ab794679a4d959865df1e4fe633" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "availability_time_slots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isSlotBooked" boolean NOT NULL DEFAULT false, "isSlotAvailable" boolean NOT NULL DEFAULT true, "workingDate" TIMESTAMP, "day" character varying(255) NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "ownedDigifranchise" uuid, CONSTRAINT "PK_054bcc5544631a8dc3641f31658" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "asset" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "purchasePrice" numeric(10,2) NOT NULL, "purchaseDate" TIMESTAMP NOT NULL DEFAULT now(), "depreciationRate" integer NOT NULL, "currentValue" numeric(10,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "franchiseId" uuid, CONSTRAINT "PK_1209d107fe21482beaea51b745e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "operating_parameters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "salesPaidByCreditCard" numeric(5,2) NOT NULL, "salesMadeOnCredit" numeric(5,2) NOT NULL, "averageCreditorTerms" integer NOT NULL, "averageDebtorTerms" integer NOT NULL, "operatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "franchiseId" uuid, CONSTRAINT "PK_10e28996d81cb21f85abb2975fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "income" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "source" character varying(255) NOT NULL, "quantity" integer NOT NULL, "unityCost" numeric(10,2) NOT NULL, "totalAmount" numeric(10,2) NOT NULL, "description" character varying(255) NOT NULL, "incomeDate" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "franchiseId" uuid, CONSTRAINT "PK_29a10f17b97568f70cee8586d58" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "funding" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "source" character varying NOT NULL, "monthReceived" integer NOT NULL, "repaymentTerm" integer NOT NULL, "annualInterestRate" numeric(5,2) NOT NULL, "fundedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "franchiseId" uuid, CONSTRAINT "PK_096afc0d11a08deb52da61f039e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."expense_arrangement_enum" AS ENUM('cash', 'credit')`);
        await queryRunner.query(`CREATE TABLE "expense" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "arrangement" "public"."expense_arrangement_enum" NOT NULL DEFAULT 'cash', "monthlyExpense" json NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "franchiseId" uuid, "fixedExpenseId" uuid, CONSTRAINT "PK_edd925b450e13ea36197c9590fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "deposit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "item" character varying NOT NULL, "monthPaid" integer NOT NULL, "monthRecovered" integer NOT NULL, "depositAmount" numeric(10,2) NOT NULL, "depositedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, "franchiseId" uuid, CONSTRAINT "PK_6654b4be449dadfd9d03a324b61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_3d2f174ef04fb312fdebd0ddc53" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_c28e52f758e7bbc53828db92194" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_dc18daa696860586ba4667a9d31" FOREIGN KEY ("statusId") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_management" ADD CONSTRAINT "FK_3fb9db823129e304bfbfb410330" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_management" ADD CONSTRAINT "FK_10906938e9cd926e0bc37509f57" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_management" ADD CONSTRAINT "FK_5d3d07103609a552f70249dfc36" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_management" ADD CONSTRAINT "FK_75694810d2bd701945c948c0316" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_general_info" ADD CONSTRAINT "FK_628ee3d8e80b874079732697d61" FOREIGN KEY ("ownedDigifranchiseId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_compliance_info" ADD CONSTRAINT "FK_aaf18ed9b15cc56f76043dc0d5a" FOREIGN KEY ("ownedDigifranchiseId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_service_category" ADD CONSTRAINT "FK_240b0c23c7c4f0edf38fb827910" FOREIGN KEY ("serviceId") REFERENCES "digifranchise_service_offered"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotations" ADD CONSTRAINT "FK_1e5666c02e55fcd05929281b3c0" FOREIGN KEY ("ownedDigifranchiseId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotationItems" ADD CONSTRAINT "FK_c4e72ddcc79948854d899c6d921" FOREIGN KEY ("quotation") REFERENCES "quotations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotationItems" ADD CONSTRAINT "FK_893b14ad6d727b295916c0924bb" FOREIGN KEY ("product") REFERENCES "digifranchise_product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotationItems" ADD CONSTRAINT "FK_ed98d75f79f2f3753c1812bd1c3" FOREIGN KEY ("service") REFERENCES "digifranchise_service_offered"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_product" ADD CONSTRAINT "FK_73cb62e2abf8bae34a6d5d77b98" FOREIGN KEY ("digifranchiseId") REFERENCES "digifranchise"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_product" ADD CONSTRAINT "FK_2048ea591b1711535d7a82bad36" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_product" ADD CONSTRAINT "FK_33f947c917ed59e29f91cde45a3" FOREIGN KEY ("digifranchiseOwnedId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_select_product_or_service_table" ADD CONSTRAINT "FK_e40d756cb6e557a2a269b01276e" FOREIGN KEY ("ownerDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_select_product_or_service_table" ADD CONSTRAINT "FK_c80c8767cedc790c17243a5e57a" FOREIGN KEY ("digifranchiseService") REFERENCES "digifranchise_service_offered"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_select_product_or_service_table" ADD CONSTRAINT "FK_a730ef63a5affd24044c4134030" FOREIGN KEY ("franchiseProduct") REFERENCES "digifranchise_product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_select_product_or_service_table" ADD CONSTRAINT "FK_d8bcabd27efae3b578e215182ee" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_service_offered" ADD CONSTRAINT "FK_211f3143b8b2f126098ede2f5c1" FOREIGN KEY ("digifranchiseId") REFERENCES "digifranchise"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_service_offered" ADD CONSTRAINT "FK_c4729ec60a40846cd2c5415828a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_service_offered" ADD CONSTRAINT "FK_0295f3e699e0bd609406f57f3d5" FOREIGN KEY ("digifranchiseOwnedId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_sub_product" ADD CONSTRAINT "FK_60e78e864a4429c58348e3a2845" FOREIGN KEY ("digifranchiseProductId") REFERENCES "digifranchise_product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_sub_product" ADD CONSTRAINT "FK_2f17c791672d285095180d2dfc1" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_sub_product" ADD CONSTRAINT "FK_2135ef637158302a406973e7335" FOREIGN KEY ("digifranchiseOwnedId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_sub_service_category" ADD CONSTRAINT "FK_5d9c767ba9555106fa4f3987e43" FOREIGN KEY ("subServiceId") REFERENCES "digifranchise_sub_services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_sub_services" ADD CONSTRAINT "FK_df1712e88c792388ca3f60e14d3" FOREIGN KEY ("digifranchiseServiceId") REFERENCES "digifranchise_service_offered"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_sub_services" ADD CONSTRAINT "FK_120377ed67b54c72cd2c0b95660" FOREIGN KEY ("digifranchiseOwnedId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_sub_services" ADD CONSTRAINT "FK_49a8550befbc41e3dd2aed09998" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_gallery_image" ADD CONSTRAINT "FK_2f7e6c72ac59db3b9e5e702a556" FOREIGN KEY ("digifranchiseServiceId") REFERENCES "digifranchise_service_offered"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_gallery_image" ADD CONSTRAINT "FK_b421043cbc4ef6382596af55390" FOREIGN KEY ("digifranchiseProductId") REFERENCES "digifranchise_product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_gallery_image" ADD CONSTRAINT "FK_ca0bd1fb94e3f5a14c72bdcb7d2" FOREIGN KEY ("subServiceId") REFERENCES "digifranchise_sub_services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_gallery_image" ADD CONSTRAINT "FK_d6c2685873d63d3395e9dcb9b1f" FOREIGN KEY ("subProductId") REFERENCES "digifranchise_sub_product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_gallery_image" ADD CONSTRAINT "FK_68c771d0efb4ca7a15b96d217b0" FOREIGN KEY ("digifranchiseOwnedId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fixed_expense_category" ADD CONSTRAINT "FK_a575d50e871d42879a93d145f09" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_expense" ADD CONSTRAINT "FK_465375308d5b5d8079a4d9e933d" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_expense" ADD CONSTRAINT "FK_c07ad4355ea31f770f26a0d3b9d" FOREIGN KEY ("fixedExpense") REFERENCES "fixed_expense_category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "available_management" ADD CONSTRAINT "FK_faa4f1caf364e05551ae79b94e1" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "available_management" ADD CONSTRAINT "FK_1d9bee1b1bccfe03eeb99125cc8" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unavailable_management" ADD CONSTRAINT "FK_275edb612f04767efbb286ce63f" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unavailable_management" ADD CONSTRAINT "FK_c7f0f8d0a16f5c15da0f0dcd648" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unavailable_management" ADD CONSTRAINT "FK_9dbf38c49944741370eabe3e2d5" FOREIGN KEY ("AvailableManagementId") REFERENCES "available_management"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_management" ADD CONSTRAINT "FK_533b0a815c8195e11ace856ae16" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_management" ADD CONSTRAINT "FK_550779654f6c0c5419de37a3157" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_management" ADD CONSTRAINT "FK_cdeb26c1e7f66aeda069b76e967" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_management" ADD CONSTRAINT "FK_9878b0458c861b1fc94f1688eb8" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calender_venue" ADD CONSTRAINT "FK_030ce5c3bf350175ee38b33c9f5" FOREIGN KEY ("ownedFranchiseId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability" ADD CONSTRAINT "FK_42a42b693f05f17e56d1d9ba93f" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability" ADD CONSTRAINT "FK_569b66bac409918e56b48ccb3dd" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_week_days" ADD CONSTRAINT "FK_86151d70a4800f8526d40811e08" FOREIGN KEY ("availabilityId") REFERENCES "availability"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_week_days" ADD CONSTRAINT "FK_9267048230c4ec77167b1d9b403" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_week_days" ADD CONSTRAINT "FK_0f4d0bb222d42ea6efc5b5085ae" FOREIGN KEY ("unavailabilityId") REFERENCES "unavailability"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_week_days" ADD CONSTRAINT "FK_8c1df98ed8d874f9284a3101ea0" FOREIGN KEY ("availabilitySlotsDetailsId") REFERENCES "availability_slots_details"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_day_time" ADD CONSTRAINT "FK_824735b6e3ed7ec5eabc9d76222" FOREIGN KEY ("weekDay") REFERENCES "availability_week_days"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_day_time" ADD CONSTRAINT "FK_1d30ef0b45d4439abf2f979a812" FOREIGN KEY ("availabilityId") REFERENCES "availability"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_day_time" ADD CONSTRAINT "FK_d9a22f2c75d17c24d40482df349" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_day_time" ADD CONSTRAINT "FK_ae2d7e60007de6eca161274a97a" FOREIGN KEY ("availabilitySlotsDetailsId") REFERENCES "availability_slots_details"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unavailability" ADD CONSTRAINT "FK_e21814e44acef02ccba5977885f" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unavailability" ADD CONSTRAINT "FK_392835dc095933a11e48fe99901" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unavailability" ADD CONSTRAINT "FK_69da644f9ad6db633ec12577f59" FOREIGN KEY ("availabilityWeekDaysId") REFERENCES "availability_week_days"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unavailability" ADD CONSTRAINT "FK_614e5860cbaab23cdf0fbd6b89c" FOREIGN KEY ("availabilityId") REFERENCES "availability"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_slots_details" ADD CONSTRAINT "FK_c2b553ce6ea8024db0c0ebd76bc" FOREIGN KEY ("availabilityDayTime") REFERENCES "availability_day_time"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_slots_details" ADD CONSTRAINT "FK_37207487c424dc59d9f0de59db5" FOREIGN KEY ("availabilityWeekDays") REFERENCES "availability_week_days"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_slots_details" ADD CONSTRAINT "FK_f8b867f7eb949923c2797c99a26" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_slots_details" ADD CONSTRAINT "FK_d6097137fe87e90a09d934e3970" FOREIGN KEY ("availabilityId") REFERENCES "availability"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_slots_time_one_one" ADD CONSTRAINT "FK_45762ce41e7b96dc7853810b7d6" FOREIGN KEY ("availabilityDayTime") REFERENCES "availability_day_time"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_slots_time_one_one" ADD CONSTRAINT "FK_5f874121cc3db70869721cbec08" FOREIGN KEY ("availabilityWeekDays") REFERENCES "availability_week_days"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_slots_time_one_one" ADD CONSTRAINT "FK_9136759e57e7557937afdfa3075" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_slots_time_one_one" ADD CONSTRAINT "FK_c55830852b43c72edaa1c87ef5d" FOREIGN KEY ("availabilityId") REFERENCES "availability"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_booked_slots" ADD CONSTRAINT "FK_f5b7fc82f02c5c427647d18b030" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_booked_slots" ADD CONSTRAINT "FK_89b14ce607290844cbfb4daa20a" FOREIGN KEY ("slotId") REFERENCES "availability_slots_time_one_one"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_working_hours" ADD CONSTRAINT "FK_481065189f21e163c70e1caa6a7" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_owner" ADD CONSTRAINT "FK_b2c9c5f59fbc93fddca4c7afa29" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digifranchise_owner" ADD CONSTRAINT "FK_804ff656af3f03a41f206f3ae0b" FOREIGN KEY ("digifranchise") REFERENCES "digifranchise"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_issue_table" ADD CONSTRAINT "FK_d77b800ac159a65e4e542feb3e3" FOREIGN KEY ("orderId") REFERENCES "order_table"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_complaints_table" ADD CONSTRAINT "FK_47d268f47796be2a8d448f35e1a" FOREIGN KEY ("orderId") REFERENCES "order_table"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_complaints_table" ADD CONSTRAINT "FK_70176ad9a5bb2122201f8f523aa" FOREIGN KEY ("orderIssueId") REFERENCES "order_issue_table"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_table" ADD CONSTRAINT "FK_6702e6613ff095d78ca480e326a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_table" ADD CONSTRAINT "FK_2123af1e640c6ebb5916bac50d7" FOREIGN KEY ("productId") REFERENCES "digifranchise_product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_table" ADD CONSTRAINT "FK_ad92edbae545f0be95b4a1d45dc" FOREIGN KEY ("serviceId") REFERENCES "digifranchise_service_offered"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_table" ADD CONSTRAINT "FK_a8a4aa6db3ecccb543a8e083e0a" FOREIGN KEY ("subProduct") REFERENCES "digifranchise_sub_product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_table" ADD CONSTRAINT "FK_7170f7687d93372cc0c1adffc68" FOREIGN KEY ("subService") REFERENCES "digifranchise_sub_services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_table" ADD CONSTRAINT "FK_18bd338852524484a32f3795ab7" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_basic_info" ADD CONSTRAINT "FK_200ab288cdef21ff36691b96d9b" FOREIGN KEY ("order") REFERENCES "order_table"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rating_order_table" ADD CONSTRAINT "FK_7f0dc3a05b9990e9e73a2dfb0b4" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rating_order_table" ADD CONSTRAINT "FK_bfde6b1c736cdbe135d4ee0216a" FOREIGN KEY ("orderId") REFERENCES "order_table"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accreditation" ADD CONSTRAINT "FK_5f268144b7f3d54e3cf668d1c65" FOREIGN KEY ("professionalBodyId") REFERENCES "professional_body_entity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" ADD CONSTRAINT "FK_6966c038058689cd59a10abe09d" FOREIGN KEY ("inventoryId") REFERENCES "inventory"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enquiries_table" ADD CONSTRAINT "FK_a4174084afa043704b26c846f45" FOREIGN KEY ("digifranchiseOwnerId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_subscription" ADD CONSTRAINT "FK_19265fb72d392fa655e6dc7f1dd" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_subscription" ADD CONSTRAINT "FK_b4059529c205d91c7d138685b55" FOREIGN KEY ("digifranchiseOwnerId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultation_table" ADD CONSTRAINT "FK_f67ef7b57cf158bdbd6da2ad380" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calender_event_guest" ADD CONSTRAINT "FK_3f8676d72b00c305f1742696a4c" FOREIGN KEY ("customerId") REFERENCES "customer_management"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calender_event_guest" ADD CONSTRAINT "FK_191f99a2329d5b373c99aa15acf" FOREIGN KEY ("eventId") REFERENCES "calender_events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calender_events" ADD CONSTRAINT "FK_8dcf9df603d9c9518fcff8b2c97" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calender_events" ADD CONSTRAINT "FK_31fe3b9d74c21abf76543517a5b" FOREIGN KEY ("venueId") REFERENCES "calender_venue"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calender_event_owner" ADD CONSTRAINT "FK_3b743b740c6fc7d9a878068b35b" FOREIGN KEY ("eventId") REFERENCES "calender_events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calender_event_owner" ADD CONSTRAINT "FK_8603f0c977af720afb503d38a3e" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calender_booking" ADD CONSTRAINT "FK_309e58e3659640e2ceae92be3c8" FOREIGN KEY ("eventId") REFERENCES "calender_events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calender_booking" ADD CONSTRAINT "FK_e095452ab2941b5b87858e39648" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_time_slots" ADD CONSTRAINT "FK_0bb10729628acb8766a41785e37" FOREIGN KEY ("ownedDigifranchise") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset" ADD CONSTRAINT "FK_1e0bf855767085f945f8f5be914" FOREIGN KEY ("franchiseId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "operating_parameters" ADD CONSTRAINT "FK_2dfa15ee5f0642edd7284c7f550" FOREIGN KEY ("franchiseId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "income" ADD CONSTRAINT "FK_e52374c32a401dffbe43b2e0a03" FOREIGN KEY ("franchiseId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "funding" ADD CONSTRAINT "FK_67a5d7184b00fb46d0fce87b613" FOREIGN KEY ("franchiseId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense" ADD CONSTRAINT "FK_e84934482e42bb311c168a725c3" FOREIGN KEY ("franchiseId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense" ADD CONSTRAINT "FK_c65a872a294e35ecc04521cc89c" FOREIGN KEY ("fixedExpenseId") REFERENCES "fixed_expense_category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deposit" ADD CONSTRAINT "FK_b32f49db1bca4fe35989d2af5d7" FOREIGN KEY ("franchiseId") REFERENCES "digifranchise_owner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "deposit" DROP CONSTRAINT "FK_b32f49db1bca4fe35989d2af5d7"`);
        await queryRunner.query(`ALTER TABLE "expense" DROP CONSTRAINT "FK_c65a872a294e35ecc04521cc89c"`);
        await queryRunner.query(`ALTER TABLE "expense" DROP CONSTRAINT "FK_e84934482e42bb311c168a725c3"`);
        await queryRunner.query(`ALTER TABLE "funding" DROP CONSTRAINT "FK_67a5d7184b00fb46d0fce87b613"`);
        await queryRunner.query(`ALTER TABLE "income" DROP CONSTRAINT "FK_e52374c32a401dffbe43b2e0a03"`);
        await queryRunner.query(`ALTER TABLE "operating_parameters" DROP CONSTRAINT "FK_2dfa15ee5f0642edd7284c7f550"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP CONSTRAINT "FK_1e0bf855767085f945f8f5be914"`);
        await queryRunner.query(`ALTER TABLE "availability_time_slots" DROP CONSTRAINT "FK_0bb10729628acb8766a41785e37"`);
        await queryRunner.query(`ALTER TABLE "calender_booking" DROP CONSTRAINT "FK_e095452ab2941b5b87858e39648"`);
        await queryRunner.query(`ALTER TABLE "calender_booking" DROP CONSTRAINT "FK_309e58e3659640e2ceae92be3c8"`);
        await queryRunner.query(`ALTER TABLE "calender_event_owner" DROP CONSTRAINT "FK_8603f0c977af720afb503d38a3e"`);
        await queryRunner.query(`ALTER TABLE "calender_event_owner" DROP CONSTRAINT "FK_3b743b740c6fc7d9a878068b35b"`);
        await queryRunner.query(`ALTER TABLE "calender_events" DROP CONSTRAINT "FK_31fe3b9d74c21abf76543517a5b"`);
        await queryRunner.query(`ALTER TABLE "calender_events" DROP CONSTRAINT "FK_8dcf9df603d9c9518fcff8b2c97"`);
        await queryRunner.query(`ALTER TABLE "calender_event_guest" DROP CONSTRAINT "FK_191f99a2329d5b373c99aa15acf"`);
        await queryRunner.query(`ALTER TABLE "calender_event_guest" DROP CONSTRAINT "FK_3f8676d72b00c305f1742696a4c"`);
        await queryRunner.query(`ALTER TABLE "consultation_table" DROP CONSTRAINT "FK_f67ef7b57cf158bdbd6da2ad380"`);
        await queryRunner.query(`ALTER TABLE "customer_subscription" DROP CONSTRAINT "FK_b4059529c205d91c7d138685b55"`);
        await queryRunner.query(`ALTER TABLE "customer_subscription" DROP CONSTRAINT "FK_19265fb72d392fa655e6dc7f1dd"`);
        await queryRunner.query(`ALTER TABLE "enquiries_table" DROP CONSTRAINT "FK_a4174084afa043704b26c846f45"`);
        await queryRunner.query(`ALTER TABLE "inventory_entries" DROP CONSTRAINT "FK_6966c038058689cd59a10abe09d"`);
        await queryRunner.query(`ALTER TABLE "accreditation" DROP CONSTRAINT "FK_5f268144b7f3d54e3cf668d1c65"`);
        await queryRunner.query(`ALTER TABLE "rating_order_table" DROP CONSTRAINT "FK_bfde6b1c736cdbe135d4ee0216a"`);
        await queryRunner.query(`ALTER TABLE "rating_order_table" DROP CONSTRAINT "FK_7f0dc3a05b9990e9e73a2dfb0b4"`);
        await queryRunner.query(`ALTER TABLE "order_basic_info" DROP CONSTRAINT "FK_200ab288cdef21ff36691b96d9b"`);
        await queryRunner.query(`ALTER TABLE "order_table" DROP CONSTRAINT "FK_18bd338852524484a32f3795ab7"`);
        await queryRunner.query(`ALTER TABLE "order_table" DROP CONSTRAINT "FK_7170f7687d93372cc0c1adffc68"`);
        await queryRunner.query(`ALTER TABLE "order_table" DROP CONSTRAINT "FK_a8a4aa6db3ecccb543a8e083e0a"`);
        await queryRunner.query(`ALTER TABLE "order_table" DROP CONSTRAINT "FK_ad92edbae545f0be95b4a1d45dc"`);
        await queryRunner.query(`ALTER TABLE "order_table" DROP CONSTRAINT "FK_2123af1e640c6ebb5916bac50d7"`);
        await queryRunner.query(`ALTER TABLE "order_table" DROP CONSTRAINT "FK_6702e6613ff095d78ca480e326a"`);
        await queryRunner.query(`ALTER TABLE "order_complaints_table" DROP CONSTRAINT "FK_70176ad9a5bb2122201f8f523aa"`);
        await queryRunner.query(`ALTER TABLE "order_complaints_table" DROP CONSTRAINT "FK_47d268f47796be2a8d448f35e1a"`);
        await queryRunner.query(`ALTER TABLE "order_issue_table" DROP CONSTRAINT "FK_d77b800ac159a65e4e542feb3e3"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_owner" DROP CONSTRAINT "FK_804ff656af3f03a41f206f3ae0b"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_owner" DROP CONSTRAINT "FK_b2c9c5f59fbc93fddca4c7afa29"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_working_hours" DROP CONSTRAINT "FK_481065189f21e163c70e1caa6a7"`);
        await queryRunner.query(`ALTER TABLE "availability_booked_slots" DROP CONSTRAINT "FK_89b14ce607290844cbfb4daa20a"`);
        await queryRunner.query(`ALTER TABLE "availability_booked_slots" DROP CONSTRAINT "FK_f5b7fc82f02c5c427647d18b030"`);
        await queryRunner.query(`ALTER TABLE "availability_slots_time_one_one" DROP CONSTRAINT "FK_c55830852b43c72edaa1c87ef5d"`);
        await queryRunner.query(`ALTER TABLE "availability_slots_time_one_one" DROP CONSTRAINT "FK_9136759e57e7557937afdfa3075"`);
        await queryRunner.query(`ALTER TABLE "availability_slots_time_one_one" DROP CONSTRAINT "FK_5f874121cc3db70869721cbec08"`);
        await queryRunner.query(`ALTER TABLE "availability_slots_time_one_one" DROP CONSTRAINT "FK_45762ce41e7b96dc7853810b7d6"`);
        await queryRunner.query(`ALTER TABLE "availability_slots_details" DROP CONSTRAINT "FK_d6097137fe87e90a09d934e3970"`);
        await queryRunner.query(`ALTER TABLE "availability_slots_details" DROP CONSTRAINT "FK_f8b867f7eb949923c2797c99a26"`);
        await queryRunner.query(`ALTER TABLE "availability_slots_details" DROP CONSTRAINT "FK_37207487c424dc59d9f0de59db5"`);
        await queryRunner.query(`ALTER TABLE "availability_slots_details" DROP CONSTRAINT "FK_c2b553ce6ea8024db0c0ebd76bc"`);
        await queryRunner.query(`ALTER TABLE "unavailability" DROP CONSTRAINT "FK_614e5860cbaab23cdf0fbd6b89c"`);
        await queryRunner.query(`ALTER TABLE "unavailability" DROP CONSTRAINT "FK_69da644f9ad6db633ec12577f59"`);
        await queryRunner.query(`ALTER TABLE "unavailability" DROP CONSTRAINT "FK_392835dc095933a11e48fe99901"`);
        await queryRunner.query(`ALTER TABLE "unavailability" DROP CONSTRAINT "FK_e21814e44acef02ccba5977885f"`);
        await queryRunner.query(`ALTER TABLE "availability_day_time" DROP CONSTRAINT "FK_ae2d7e60007de6eca161274a97a"`);
        await queryRunner.query(`ALTER TABLE "availability_day_time" DROP CONSTRAINT "FK_d9a22f2c75d17c24d40482df349"`);
        await queryRunner.query(`ALTER TABLE "availability_day_time" DROP CONSTRAINT "FK_1d30ef0b45d4439abf2f979a812"`);
        await queryRunner.query(`ALTER TABLE "availability_day_time" DROP CONSTRAINT "FK_824735b6e3ed7ec5eabc9d76222"`);
        await queryRunner.query(`ALTER TABLE "availability_week_days" DROP CONSTRAINT "FK_8c1df98ed8d874f9284a3101ea0"`);
        await queryRunner.query(`ALTER TABLE "availability_week_days" DROP CONSTRAINT "FK_0f4d0bb222d42ea6efc5b5085ae"`);
        await queryRunner.query(`ALTER TABLE "availability_week_days" DROP CONSTRAINT "FK_9267048230c4ec77167b1d9b403"`);
        await queryRunner.query(`ALTER TABLE "availability_week_days" DROP CONSTRAINT "FK_86151d70a4800f8526d40811e08"`);
        await queryRunner.query(`ALTER TABLE "availability" DROP CONSTRAINT "FK_569b66bac409918e56b48ccb3dd"`);
        await queryRunner.query(`ALTER TABLE "availability" DROP CONSTRAINT "FK_42a42b693f05f17e56d1d9ba93f"`);
        await queryRunner.query(`ALTER TABLE "calender_venue" DROP CONSTRAINT "FK_030ce5c3bf350175ee38b33c9f5"`);
        await queryRunner.query(`ALTER TABLE "staff_management" DROP CONSTRAINT "FK_9878b0458c861b1fc94f1688eb8"`);
        await queryRunner.query(`ALTER TABLE "staff_management" DROP CONSTRAINT "FK_cdeb26c1e7f66aeda069b76e967"`);
        await queryRunner.query(`ALTER TABLE "inventory_management" DROP CONSTRAINT "FK_550779654f6c0c5419de37a3157"`);
        await queryRunner.query(`ALTER TABLE "inventory_management" DROP CONSTRAINT "FK_533b0a815c8195e11ace856ae16"`);
        await queryRunner.query(`ALTER TABLE "unavailable_management" DROP CONSTRAINT "FK_9dbf38c49944741370eabe3e2d5"`);
        await queryRunner.query(`ALTER TABLE "unavailable_management" DROP CONSTRAINT "FK_c7f0f8d0a16f5c15da0f0dcd648"`);
        await queryRunner.query(`ALTER TABLE "unavailable_management" DROP CONSTRAINT "FK_275edb612f04767efbb286ce63f"`);
        await queryRunner.query(`ALTER TABLE "available_management" DROP CONSTRAINT "FK_1d9bee1b1bccfe03eeb99125cc8"`);
        await queryRunner.query(`ALTER TABLE "available_management" DROP CONSTRAINT "FK_faa4f1caf364e05551ae79b94e1"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_expense" DROP CONSTRAINT "FK_c07ad4355ea31f770f26a0d3b9d"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_expense" DROP CONSTRAINT "FK_465375308d5b5d8079a4d9e933d"`);
        await queryRunner.query(`ALTER TABLE "fixed_expense_category" DROP CONSTRAINT "FK_a575d50e871d42879a93d145f09"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_gallery_image" DROP CONSTRAINT "FK_68c771d0efb4ca7a15b96d217b0"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_gallery_image" DROP CONSTRAINT "FK_d6c2685873d63d3395e9dcb9b1f"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_gallery_image" DROP CONSTRAINT "FK_ca0bd1fb94e3f5a14c72bdcb7d2"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_gallery_image" DROP CONSTRAINT "FK_b421043cbc4ef6382596af55390"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_gallery_image" DROP CONSTRAINT "FK_2f7e6c72ac59db3b9e5e702a556"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_sub_services" DROP CONSTRAINT "FK_49a8550befbc41e3dd2aed09998"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_sub_services" DROP CONSTRAINT "FK_120377ed67b54c72cd2c0b95660"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_sub_services" DROP CONSTRAINT "FK_df1712e88c792388ca3f60e14d3"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_sub_service_category" DROP CONSTRAINT "FK_5d9c767ba9555106fa4f3987e43"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_sub_product" DROP CONSTRAINT "FK_2135ef637158302a406973e7335"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_sub_product" DROP CONSTRAINT "FK_2f17c791672d285095180d2dfc1"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_sub_product" DROP CONSTRAINT "FK_60e78e864a4429c58348e3a2845"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_service_offered" DROP CONSTRAINT "FK_0295f3e699e0bd609406f57f3d5"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_service_offered" DROP CONSTRAINT "FK_c4729ec60a40846cd2c5415828a"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_service_offered" DROP CONSTRAINT "FK_211f3143b8b2f126098ede2f5c1"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_select_product_or_service_table" DROP CONSTRAINT "FK_d8bcabd27efae3b578e215182ee"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_select_product_or_service_table" DROP CONSTRAINT "FK_a730ef63a5affd24044c4134030"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_select_product_or_service_table" DROP CONSTRAINT "FK_c80c8767cedc790c17243a5e57a"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_select_product_or_service_table" DROP CONSTRAINT "FK_e40d756cb6e557a2a269b01276e"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_product" DROP CONSTRAINT "FK_33f947c917ed59e29f91cde45a3"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_product" DROP CONSTRAINT "FK_2048ea591b1711535d7a82bad36"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_product" DROP CONSTRAINT "FK_73cb62e2abf8bae34a6d5d77b98"`);
        await queryRunner.query(`ALTER TABLE "quotationItems" DROP CONSTRAINT "FK_ed98d75f79f2f3753c1812bd1c3"`);
        await queryRunner.query(`ALTER TABLE "quotationItems" DROP CONSTRAINT "FK_893b14ad6d727b295916c0924bb"`);
        await queryRunner.query(`ALTER TABLE "quotationItems" DROP CONSTRAINT "FK_c4e72ddcc79948854d899c6d921"`);
        await queryRunner.query(`ALTER TABLE "quotations" DROP CONSTRAINT "FK_1e5666c02e55fcd05929281b3c0"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_service_category" DROP CONSTRAINT "FK_240b0c23c7c4f0edf38fb827910"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_compliance_info" DROP CONSTRAINT "FK_aaf18ed9b15cc56f76043dc0d5a"`);
        await queryRunner.query(`ALTER TABLE "digifranchise_general_info" DROP CONSTRAINT "FK_628ee3d8e80b874079732697d61"`);
        await queryRunner.query(`ALTER TABLE "customer_management" DROP CONSTRAINT "FK_75694810d2bd701945c948c0316"`);
        await queryRunner.query(`ALTER TABLE "customer_management" DROP CONSTRAINT "FK_5d3d07103609a552f70249dfc36"`);
        await queryRunner.query(`ALTER TABLE "supplier_management" DROP CONSTRAINT "FK_10906938e9cd926e0bc37509f57"`);
        await queryRunner.query(`ALTER TABLE "supplier_management" DROP CONSTRAINT "FK_3fb9db823129e304bfbfb410330"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_dc18daa696860586ba4667a9d31"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_c28e52f758e7bbc53828db92194"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_3d2f174ef04fb312fdebd0ddc53"`);
        await queryRunner.query(`DROP TABLE "deposit"`);
        await queryRunner.query(`DROP TABLE "expense"`);
        await queryRunner.query(`DROP TYPE "public"."expense_arrangement_enum"`);
        await queryRunner.query(`DROP TABLE "funding"`);
        await queryRunner.query(`DROP TABLE "income"`);
        await queryRunner.query(`DROP TABLE "operating_parameters"`);
        await queryRunner.query(`DROP TABLE "asset"`);
        await queryRunner.query(`DROP TABLE "availability_time_slots"`);
        await queryRunner.query(`DROP TABLE "calender_booking"`);
        await queryRunner.query(`DROP TYPE "public"."calender_booking_status_enum"`);
        await queryRunner.query(`DROP TABLE "calender_event_owner"`);
        await queryRunner.query(`DROP TABLE "calender_events"`);
        await queryRunner.query(`DROP TABLE "calender_event_guest"`);
        await queryRunner.query(`DROP TABLE "consultation_table"`);
        await queryRunner.query(`DROP TABLE "digifranchise_professional_body_membership"`);
        await queryRunner.query(`DROP TABLE "customer_subscription"`);
        await queryRunner.query(`DROP TABLE "enquiries_table"`);
        await queryRunner.query(`DROP TABLE "file"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`DROP TABLE "inventory_entries"`);
        await queryRunner.query(`DROP TABLE "rate_table"`);
        await queryRunner.query(`DROP TABLE "professional_body_entity"`);
        await queryRunner.query(`DROP TABLE "accreditation"`);
        await queryRunner.query(`DROP TABLE "rating_order_table"`);
        await queryRunner.query(`DROP TABLE "order_basic_info"`);
        await queryRunner.query(`DROP TABLE "order_table"`);
        await queryRunner.query(`DROP TYPE "public"."order_table_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_complaints_table"`);
        await queryRunner.query(`DROP TABLE "order_issue_table"`);
        await queryRunner.query(`DROP TABLE "digifranchise_owner"`);
        await queryRunner.query(`DROP TABLE "digifranchise_working_hours"`);
        await queryRunner.query(`DROP TYPE "public"."digifranchise_working_hours_breaktimebetweenbookedslots_enum"`);
        await queryRunner.query(`DROP TYPE "public"."digifranchise_working_hours_allowedtimeslotunits_enum"`);
        await queryRunner.query(`DROP TABLE "availability_booked_slots"`);
        await queryRunner.query(`DROP TABLE "availability_slots_time_one_one"`);
        await queryRunner.query(`DROP TABLE "availability_slots_details"`);
        await queryRunner.query(`DROP TABLE "unavailability"`);
        await queryRunner.query(`DROP TABLE "availability_day_time"`);
        await queryRunner.query(`DROP TABLE "availability_week_days"`);
        await queryRunner.query(`DROP TABLE "availability"`);
        await queryRunner.query(`DROP TYPE "public"."availability_breaktimebetweenbookedslots_enum"`);
        await queryRunner.query(`DROP TYPE "public"."availability_allowedtimeslotunits_enum"`);
        await queryRunner.query(`DROP TABLE "calender_venue"`);
        await queryRunner.query(`DROP TABLE "staff_management"`);
        await queryRunner.query(`DROP TABLE "inventory_management"`);
        await queryRunner.query(`DROP TABLE "unavailable_management"`);
        await queryRunner.query(`DROP TABLE "available_management"`);
        await queryRunner.query(`DROP TYPE "public"."available_management_mintimebetweenbookedslots_enum"`);
        await queryRunner.query(`DROP TYPE "public"."available_management_allowedtimeslotunits_enum"`);
        await queryRunner.query(`DROP TABLE "digifranchise_expense"`);
        await queryRunner.query(`DROP TABLE "fixed_expense_category"`);
        await queryRunner.query(`DROP TABLE "digifranchise_gallery_image"`);
        await queryRunner.query(`DROP TABLE "digifranchise_sub_services"`);
        await queryRunner.query(`DROP TABLE "digifranchise_sub_service_category"`);
        await queryRunner.query(`DROP TABLE "digifranchise_sub_product"`);
        await queryRunner.query(`DROP TABLE "digifranchise_service_offered"`);
        await queryRunner.query(`DROP TABLE "digifranchise_select_product_or_service_table"`);
        await queryRunner.query(`DROP TABLE "digifranchise_product"`);
        await queryRunner.query(`DROP TABLE "quotationItems"`);
        await queryRunner.query(`DROP TABLE "quotations"`);
        await queryRunner.query(`DROP TABLE "digifranchise_service_category"`);
        await queryRunner.query(`DROP TABLE "digifranchise_compliance_info"`);
        await queryRunner.query(`DROP TABLE "digifranchise_general_info"`);
        await queryRunner.query(`DROP TABLE "digifranchise"`);
        await queryRunner.query(`DROP TABLE "customer_management"`);
        await queryRunner.query(`DROP TABLE "supplier_management"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5e03f420f37f1f2270ec3f7a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_772c766ebfc783bb03fa5e3404"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_083056026899d829066008244b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9086fd0adfc3fdd84a443dd1b1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91c1ef85a7e6c89eaeec99bfd6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0f3f1de3c7590ddf4299b6596"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d03cc9951fbb73d092fa53127e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bd3f2e16165d1dac3e8e13286"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0e1b4ecdca13b177e2e3a0613"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58e4dbff0e1a32a9bdc861bb29"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9bd2fe7a8e694dedc4ec2f666f"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d2f174ef04fb312fdebd0ddc5"`);
        await queryRunner.query(`DROP TABLE "session"`);
        await queryRunner.query(`DROP TABLE "status"`);
        await queryRunner.query(`DROP TABLE "role"`);
    }

}
